-- v3.0.0_2 - Catálogo de idiomas y textos i18n
--
-- Recuperado de los INSERT de las migraciones V2.0.0 de Commons-Engine y CAH-Engine, que
-- estaban intactos aunque el DDL que los rodeaba estuviera corrompido.
--
-- Cuatro tags aparecían en ambas fuentes con textos distintos; se ha escogido la variante
-- acentuada y la que concuerda con el significado del tag (ERROR_PLAYER_ALREADY_VOTED_DELETION
-- decía 'Ya has votado una carta', que es de otra cosa).
--
-- Y ocho textos son nuevos: el código los pedía pero no estaban en ninguna migración, así que
-- al usuario se le enseñaba el nombre del tag en crudo.

INSERT INTO lang (id, name) VALUES ('es', 'Español'), ('en', 'English');

INSERT INTO tag (tag, lang_id, text) VALUES
    ('ACCEPT', 'es', 'Aceptar'),
    ('ALL_MESSAGES_SENT', 'es', 'Se han enviado todos los mensajes.'),
    ('CANCEL', 'es', 'Cancelar'),
    ('CARDS_BLACK_ADD_BUTTON', 'es', 'Añadir cartas negras'),
    ('CARDS_BLACK_CARD_ADD', 'es', 'Respondeme con el texto de la carta negra que deseas añadir.'),
    ('CARDS_BLACK_CARD_ADDED', 'es', 'Carta negra añadida correctamente. Llevas {0} de {1}.'),
    ('CARDS_BLACK_CARD_ADD_ANOTHER', 'es', 'Respondeme con el texto de la carta negra que deseas añadir o escribe :cancel: para volver al menú.'),
    ('CARDS_BLACK_CARD_DELETE', 'es', 'Respondeme con el número de la carta blanca que deseas borrar.'),
    ('CARDS_BLACK_CARD_DELETED', 'es', 'Carta blanca borrada correctamente.'),
    ('CARDS_BLACK_CARD_EDIT', 'es', 'Respondeme con el número de la carta blanca que deseas editar.'),
    ('CARDS_BLACK_CARD_EDITED', 'es', 'Carta blanca editada correctamente.'),
    ('CARDS_BLACK_CARD_EDIT_NEW_TEXT', 'es', 'Respondeme con el nuevo texto que quieres para esa carta.'),
    ('CARDS_BLACK_EDIT_BUTTON', 'es', 'Editar carta negra'),
    ('CARDS_BLACK_LIST', 'es', '¡Marchando! Aqui tienes las cartas negras. (Es posible que se envien en varios mensajes)'),
    ('CARDS_BLACK_LIST_BUTTON', 'es', 'Listar cartas negras'),
    ('CARDS_BLACK_LIST_END', 'es', 'Esas son todas las cartas negras.'),
    ('CARDS_BLACK_REMOVE_BUTTON', 'es', 'Borrar carta negra'),
    ('CARDS_MENU', 'es', 'Estas gestionando las cartas del diccionario: {0}'),
    ('CARDS_WHITE_ADD_BUTTON', 'es', 'Añadir cartas blancas'),
    ('CARDS_WHITE_CARD_ADD', 'es', 'Respondeme con el texto de la carta blanca que deseas añadir.'),
    ('CARDS_WHITE_CARD_ADDED', 'es', 'Carta blanca añadida correctamente. Llevas {0} de {1}.'),
    ('CARDS_WHITE_CARD_ADD_ANOTHER', 'es', 'Respondeme con el texto de la carta blanca que deseas añadir o escribe :cancel: para volver al menú.'),
    ('CARDS_WHITE_CARD_DELETE', 'es', 'Respondeme con el número de la carta blanca que deseas borrar.'),
    ('CARDS_WHITE_CARD_DELETED', 'es', 'Carta blanca borrada correctamente.'),
    ('CARDS_WHITE_CARD_EDIT', 'es', 'Respondeme con el número de la carta blanca que deseas editar.'),
    ('CARDS_WHITE_CARD_EDITED', 'es', 'Carta blanca editada correctamente.'),
    ('CARDS_WHITE_CARD_EDIT_NEW_TEXT', 'es', 'Respondeme con el nuevo texto que quieres para esa carta.'),
    ('CARDS_WHITE_EDIT_BUTTON', 'es', 'Editar carta blanca'),
    ('CARDS_WHITE_LIST', 'es', '¡Marchando! Aqui tienes las cartas blancas. (Es posible que se envien en varios mensajes)'),
    ('CARDS_WHITE_LIST_BUTTON', 'es', 'Listar cartas blancas'),
    ('CARDS_WHITE_LIST_END', 'es', 'Esas son todas las cartas blancas.'),
    ('CARDS_WHITE_REMOVE_BUTTON', 'es', 'Borrar carta blanca'),
    ('COLLABORATORS_ACCEPTED_CREATOR', 'es', '{0} ha aceptado ser colaborador.'),
    ('COLLABORATORS_ACCEPTED_MESSAGE', 'es', '¡Perfecto! Ya eres colaborador, ahora pide al creador del bot que te active.'),
    ('COLLABORATORS_ACCEPT_MESSAGE', 'es', '{0} te ha invitado a colaborar en su diccionario {1}.'),
    ('COLLABORATORS_ADD', 'es', '¡Vamos a ello! Dime el nombre (p.ej. @cclhbot) o el id (puedes obtenerlo con el comando /getmyid) del usuario que deseas añadir como colaborador.\n\n<b>OJO: El colaborador que desees añadir debe haber iniciado este bot de diccionarios primero (escribiendole /start por privado)</b>'),
    ('COLLABORATORS_ADDED', 'es', 'Se ha enviado una invitación de colaborador a {0} correctamente. Ahora deberá aceptar la invitación.'),
    ('COLLABORATORS_ADD_BUTTON', 'es', 'Añadir colaborador'),
    ('COLLABORATORS_DELETE', 'es', '¡Vamos a ello! Dime el nombre (p.ej. @cclhbot) o el id (puedes obtenerlo con el comando /getmyid) del usuario que deseas eliminar como colaborador.'),
    ('COLLABORATORS_DELETED', 'es', 'Se ha eliminado el colaborador correctamente.'),
    ('COLLABORATORS_DELETED_MESSAGE', 'es', 'Te han eliminado del diccionario {0}'),
    ('COLLABORATORS_DELETE_BUTTON', 'es', 'Quitar colaborador'),
    ('COLLABORATORS_LIST', 'es', 'Estos son los colaboradores de este diccionario:\n\n{0}'),
    ('COLLABORATORS_LIST_BUTTON', 'es', 'Listar colaboradores'),
    ('COLLABORATORS_MENU', 'es', 'Estas gestionando los colaboradores del diccionario: {0}'),
    ('COLLABORATORS_REJECTED_CREATOR', 'es', '{0} ha rechazado ser colaborador.'),
    ('COLLABORATORS_REJECTED_MESSAGE', 'es', 'Has rechazado ser colaborador.'),
    ('COLLABORATORS_TOGGLE', 'es', '¡Vamos a ello! Dime el nombre (p.ej. @cclhbot) o el id (puedes obtenerlo con el comando /getmyid) del usuario que deseas activar/desactivar como colaborador.'),
    ('COLLABORATORS_TOGGLED_OFF', 'es', 'Se ha desactivado al colaborador {0} correctamente.'),
    ('COLLABORATORS_TOGGLED_OFF_MESSAGE', 'es', 'Has perdido permisos de edición en el diccionario {0}.'),
    ('COLLABORATORS_TOGGLED_ON', 'es', 'Se ha activado al colaborador {0} correctamente.'),
    ('COLLABORATORS_TOGGLED_ON_MESSAGE', 'es', 'Has recibido permisos de edición en el diccionario {0}.'),
    ('COLLABORATORS_TOGGLE_BUTTON', 'es', 'Activar/Desactivar colaborador'),
    ('COLLABORATOR_ADD_ALREADY_EXISTS', 'es', 'Ese usuario ya es colaborador de este diccionario.'),
    ('COLLABORATOR_ADD_MAX_REACHED', 'es', 'Este diccionario ya tiene el máximo de colaboradores.'),
    ('COLLABORATOR_ADD_USER_DOESNT_EXISTS', 'es', 'No existe ningún usuario con ese nombre.'),
    ('DICTIONARIES_CHANGE_LANG_LIST', 'es', 'Elige un diccionario para cambiar su idioma:\n{0}'),
    ('DICTIONARIES_CREATE_BUTTON', 'es', 'Crear diccionario'),
    ('DICTIONARIES_DELETE_BUTTON', 'es', 'Borrar diccionario'),
    ('DICTIONARIES_DELETE_LIST', 'es', 'Estos son los diccionarios que has creado:\n\n{0}\n\nAhora respondeme con el número de diccionario que deseas borrar.'),
    ('DICTIONARIES_HELP', 'es', 'Bienvenido a la ayuda de {0} versión {1}\n\nPuedes consultar la ayuda en el siguiente enlace: {2}\n\n¡¡Comparte tus diccionarios!!\n\n\nCreado por {3}.'),
    ('DICTIONARIES_LANG_BUTTON', 'es', 'Cambiar idioma'),
    ('DICTIONARIES_LIST', 'es', 'Estos son los diccionarios que has creado o eres colaborador:\n\n{0}'),
    ('DICTIONARIES_LIST_BUTTON', 'es', 'Listar mis diccionarios'),
    ('DICTIONARIES_MAIN_MENU', 'es', '¡Hola! Soy el bot de diccionarios de Cartas Contra la Humanidad.\nEstas son las acciones que puedes realizar:'),
    ('DICTIONARIES_MANAGE_CARDS_BUTTON', 'es', 'Gestionar cartas'),
    ('DICTIONARIES_MANAGE_CARDS_LIST', 'es', 'Estos son los diccionarios que has creado:\n\n{0}\n\nAhora respondeme con el número de diccionario del que deseas editar las cartas.'),
    ('DICTIONARIES_MANAGE_COLLABORATORS_LIST', 'es', 'Estos son los diccionarios que has creado:\n\n{0}\n\nAhora respondeme con el número de diccionario del que deseas editar los colaboradores.'),
    ('DICTIONARIES_MANAGE_COLLABS_BUTTON', 'es', 'Gestionar colaboradores'),
    ('DICTIONARIES_RENAME_BUTTON', 'es', 'Renombrar diccionario'),
    ('DICTIONARIES_RENAME_LIST', 'es', 'Estos son los diccionarios que has creado:\n\n{0}\n\nAhora respondeme con el número de diccionario que deseas renombrar.'),
    ('DICTIONARIES_SHARE_LIST', 'es', 'Estos son los diccionarios que has creado:\n\n{0}\n\nAhora respondeme con el número de diccionario que deseas compartir/descompartir.'),
    ('DICTIONARIES_TOGGLE_LIST', 'es', 'Estos son los diccionarios que has creado:\n\n{0}\n\nAhora respondeme con el número de diccionario que deseas publicar/despublicar.'),
    ('DICTIONARIES_TOGGLE_PUBLISH_BUTTON', 'es', 'Publicar/despublicar diccionario'),
    ('DICTIONARIES_TOGGLE_SHARE_BUTTON', 'es', 'Compartir/descompartir diccionario'),
    ('DICTIONARY_CHANGE_LANG', 'es', 'Escribe el código del lenguage que quieres elegir:\n{0}'),
    ('DICTIONARY_CREATE', 'es', '¡Vamos a ello! Dime el nombre del diccionario que quieres crear.'),
    ('DICTIONARY_CREATED', 'es', 'Tu diccionario se ha creado correctamente, ahora ve al menú para añadir las cartas.'),
    ('DICTIONARY_DELETE', 'es', '<b>¡CUIDADO! Este diccionario está PUBLICADO</b>. Se borrará el diccionario y también las <b>cartas</b> asociadas.\n\n¿Estás completamente seguro de que quieres borrarlo?\n· Responde SI para confirmar.\n· Responde cualquier otra cosa o ignora el mensaje para cancelar.'),
    ('DICTIONARY_DELETED', 'es', 'Tu diccionario se ha borrado correctamente.'),
    ('DICTIONARY_DELETE_CANCELLED', 'es', 'Se ha cancelado el borrado del diccionario.'),
    ('DICTIONARY_LANG_CHANGED', 'es', 'Se ha cambiado el idioma del diccionario'),
    ('DICTIONARY_RENAME', 'es', '¡Vamos a ello! Dime el nuevo nombre del diccionario que quieres renombrar.'),
    ('DICTIONARY_RENAMED', 'es', 'Tu diccionario se ha renombrado correctamente.'),
    ('DICTIONARY_SHARED_OFF', 'es', 'Se ha descompartido el diccionario {0} correctamente.'),
    ('DICTIONARY_SHARED_OFF_REQUEST', 'es', 'Se ha solicitado descompartir el diccionario {0}.'),
    ('DICTIONARY_SHARED_ON', 'es', 'Se ha compartido el diccionario {0} correctamente.'),
    ('DICTIONARY_SHARED_ON_REQUEST', 'es', 'Se ha solicitado compartir el diccionario {0}.'),
    ('DICTIONARY_SHARED_REJECTED', 'es', 'Se ha rechazado compartir el diccionario {0}.'),
    ('DICTIONARY_TOGGLED_OFF', 'es', 'Se ha despublicado el diccionario {0} correctamente.'),
    ('DICTIONARY_TOGGLED_ON', 'es', 'Se ha publicado el diccionario {0} correctamente.'),
    ('DICTIONARY_INFO', 'es', '{0} - {1} (<b>tuyo:</b> {2}; <b>publicado:</b> {3}; <b>compartido:</b> {4}; <b>idioma:</b> {5})'),
    ('COLLABORATOR_INFO', 'es', '{0} (aceptado: {1}, activo: {2})'),
    ('COLLABORATORS_LIST_EMPTY', 'es', 'No hay colaboradores.'),
    ('CARD_INFO', 'es', '{0} - {1}'),
    ('YES', 'es', 'Sí'),
    ('NO', 'es', 'No'),
    ('ERROR_SELECTION_INVALID', 'es', 'No he encontrado eso. Contesta con el número que aparece a la izquierda en la lista.'),
    ('GAME_GLOBAL_MESSAGES_ON', 'es', 'Mensajes globales activados.'),
    ('GAME_GLOBAL_MESSAGES_OFF', 'es', 'Mensajes globales desactivados.'),
    ('ERROR_CARD_ALREADY_PLAYED', 'es', 'Esa carta ya está jugada.'),
    ('ERROR_CARD_ALREADY_VOTED', 'es', 'Esa carta ya está votada.'),
    ('ERROR_CARD_NOT_PLAYED', 'es', 'Esa carta no se ha jugado en esta ronda.'),
    ('ERROR_PLAYER_CANNOT_PLAY_CARD', 'es', 'No puedes jugar esa carta.'),
    ('ERROR_PLAYER_CANNOT_VOTE_CARD', 'es', 'No puedes votar esa carta.'),
    ('ERROR_ROUND_PRESIDENT_CANNOT_PLAY_CARD', 'es', 'Esta ronda te toca elegir la carta ganadora, no jugar.'),
    ('ERROR_ROUND_NOT_FOUND', 'es', 'Esta ronda ya no está en juego.'),
    ('ERROR_ROUND_NOT_STARTED', 'es', 'La ronda todavía no ha empezado.'),
    ('ERROR_ROUND_NOT_ENDING', 'es', 'La ronda todavía no ha terminado.'),
    ('ERROR_ROUND_WRONG_STATUS', 'es', 'Esa acción no toca ahora mismo en esta ronda.'),
    ('ERROR_GAME_NOT_FOUND', 'es', 'No hay ninguna partida en este grupo.'),
    ('ERROR_GAME_ALREADY_EXISTS', 'es', 'Ya hay una partida en este grupo.'),
    ('ERROR_GAME_CREATOR_ALREADY_EXISTS', 'es', 'Ya tienes una partida abierta en otro grupo.'),
    ('ERROR_GAME_CREATOR_CANNOT_LEAVE', 'es', 'Has creado la partida: no puedes salirte, pero sí borrarla.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_PERFORM_ACTION', 'es', 'Solo quien creó la partida puede hacer eso.'),
    ('ERROR_GAME_ROOM_DOESNT_EXISTS', 'es', 'No encuentro este grupo.'),
    ('ERROR_ROOM_NOT_ACTIVE', 'es', 'Este grupo está desactivado.'),
    ('ERROR_PLAYER_NOT_FOUND', 'es', 'No estás en esta partida.'),
    ('ERROR_PLAYER_ALREADY_EXISTS', 'es', 'Ya estás en esta partida.'),
    ('ERROR_PLAYER_CANNOT_VOTE_DELETION', 'es', 'No puedes votar para borrar esta partida.'),
    ('ERROR_USER_NOT_ACTIVE', 'es', 'Tu usuario está desactivado. Escríbeme /start por privado.'),
    ('ERROR_USER_ALREADY_EXISTS', 'es', 'Ya estás registrado.'),
    ('ERROR_CANT_FIND_WINNER_CARD', 'es', 'No se ha localizado ninguna carta ganadora'),
    ('ERROR_CARD_ALREADY_EXISTS', 'es', 'Ya existe otra carta con el mismo texto en este diccionario.'),
    ('ERROR_CARD_DOESNT_EXISTS', 'es', 'La carta que intentas editar no existe.'),
    ('ERROR_CARD_EXCEEDED_LENGTH', 'es', 'La carta supera el máximo de {0} caracteres.'),
    ('ERROR_CARD_NOT_YOURS', 'es', 'Esa carta no te pertenece.'),
    ('ERROR_COLLABORATOR_ADD_ALREADY_EXISTS', 'es', 'El usuario que intentas añadir ya es colaborador en este diccionario.'),
    ('ERROR_COLLABORATOR_ADD_MAX_REACHED', 'es', 'Has alcanzado el número máximo de colaboradores y no puedes añadir más.'),
    ('ERROR_COLLABORATOR_ADD_USER_DOESNT_EXISTS', 'es', 'El usuario que intentas añadir como colaborador es incorrecto o no está registrado en el bot.'),
    ('ERROR_COLLABORATOR_DOESNT_EXISTS', 'es', 'El usuario es incorrecto o no está registrado en el bot.'),
    ('ERROR_COLLABORATOR_REMOVE_USER_DOESNT_EXISTS', 'es', 'El usuario que intentas eliminar como colaborador es incorrecto o no es colaborador en este diccionario.'),
    ('ERROR_COMMAND_SHOULD_BE_ON_GROUP', 'es', 'Este comando debe ser enviado en un grupo en el que esté el bot.'),
    ('ERROR_COMMAND_SHOULD_BE_ON_PRIVATE', 'es', 'Este comando debe ser enviado por privado al bot.'),
    ('ERROR_DICTIONARY_COLLAB_CREATOR_CANT_BE_ALTERED', 'es', 'El creador del diccionario no se puede modificar como colaborador.'),
    ('ERROR_DICTIONARY_ALREADY_EXISTS', 'es', 'Ya existe un diccionario con este nombre.'),
    ('ERROR_DICTIONARY_ALREADY_FILLED', 'es', 'No puedes añadir mas cartas de este tipo a este diccionario.'),
    ('ERROR_DICTIONARY_ALREADY_PUBLISHED', 'es', 'No puedes editar un diccionario que ya está publicado. Despublicalo para poder editarlo.'),
    ('ERROR_DICTIONARY_ALREADY_SHARED', 'es', 'No puedes modificar un diccionario que está compartido. Contacta con {0} para despublicarlo.'),
    ('ERROR_DICTIONARY_NOT_FILLED', 'es', 'No puedes publicar el diccionario porque faltan cartas de algun tipo.'),
    ('ERROR_DICTIONARY_NOT_FOUND', 'es', 'Ese diccionario no existe.'),
    ('ERROR_DICTIONARY_NOT_PUBLISHED', 'es', 'No puedes compartir un diccionario que no está publicado. Publícalo para poder compartirlo.'),
    ('ERROR_DICTIONARY_NOT_YOURS', 'es', 'Ese diccionario no te pertenece.'),
    ('ERROR_DICTIONARY_SHARED', 'es', 'El diccionario está compartido, contacta a {0} para borrarlo.'),
    ('ERROR_GAME_ALREADY_CREATED', 'es', 'Ya existe un juego activo en este grupo o el creador tiene un juego activo en otro grupo.'),
    ('ERROR_GAME_ALREADY_FILLED', 'es', 'Ya se ha superado el número máximo de jugadores.'),
    ('ERROR_GAME_ALREADY_STARTED', 'es', 'La partida ya está iniciada.'),
    ('ERROR_GAME_DOESNT_EXISTS', 'es', 'No hay ninguna partida iniciada en este grupo.'),
    ('ERROR_GAME_NOT_FILLED', 'es', 'La partida aún no ha llegado al número mínimo de jugadores.'),
    ('ERROR_GAME_NOT_STARTED', 'es', 'La partida aun no se ha iniciado.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_CONFIGURE', 'es', 'Solo el creador de la partida puede configurarla.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_DELETE', 'es', 'Solo el creador de la partida puede borrarla.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_START', 'es', 'Solo el creador de la partida puede iniciarla.'),
    ('ERROR_GAME_USER_DOESNT_EXISTS', 'es', 'No estás registrado. Escríbeme /start por privado.'),
    ('ERROR_PLAYER_ALREADY_JOINED', 'es', 'Ya estas participando en esta partida.'),
    ('ERROR_PLAYER_ALREADY_PLAYED_CARD', 'es', 'Ya has jugado una carta.'),
    ('ERROR_PLAYER_ALREADY_PLAYING', 'es', 'Ya estas participando en una partida.'),
    ('ERROR_PLAYER_ALREADY_VOTED_CARD', 'es', 'Ya has votado una carta.'),
    ('ERROR_PLAYER_ALREADY_VOTED_DELETION', 'es', 'Ya has votado para borrar esta partida.'),
    ('ERROR_PLAYER_DOES_NOT_EXISTS', 'es', 'No estas unido a ninguna partida.'),
    ('ERROR_PLAYER_NO_GAMES', 'es', 'No tienes ninguna partida activa.'),
    ('ERROR_UNKNOWN', 'es', 'Error desconocido'),
    ('ERROR_USER_ALREADY_REGISTERED', 'es', 'Ya estas registrado. Consulta /help para mas información.'),
    ('GAME_CHANGE_DICTIONARY', 'es', 'Cambiar mazo de cartas'),
    ('GAME_CHANGE_GAME_MODE', 'es', 'Cambiar modo de juego'),
    ('GAME_CHANGE_MAX_N_PLAYERS', 'es', 'Cambiar nº máximo de jugadores'),
    ('GAME_CHANGE_PUNCTUATION_MODE', 'es', 'Cambiar modo de puntuacion'),
    ('GAME_CONFIGURE_BUTTON', 'es', 'Configurar la partida'),
    ('GAME_CREATED_CURRENT_PLAYER_NUMBER', 'es', 'Se han unido estos <b>{0}</b> jugadores:'),
    ('GAME_CREATED_CURRENT_VOTE_DELETION_NUMBER', 'es', '<b>{0}</b> jugador/es han votado borrar la partida.'),
    ('GAME_CREATED_GROUP', 'es', '¡Ya he creado la partida!'),
    ('GAME_CREATING', 'es', 'Un momentito, estoy creando la partida...'),
    ('GAME_DELETED', 'es', 'Se ha borrado la partida.'),
    ('GAME_DELETE_BUTTON', 'es', 'Borrar partida'),
    ('GAME_DELETION_ALL', 'es', 'Se han borrado todas las partidas.'),
    ('GAME_DELETION_FORCED', 'es', 'Lo sentimos. Su partida ha sido borrada por la administración. Puede crear una partida nueva.'),
    ('GAME_DELETION_USER', 'es', 'Se ha borrado la partida de {0}.'),
    ('GAME_DICTIONARY_SELECT', 'es', '\nSelecciona el mazo:'),
    ('GAME_END_GAME', 'es', '¡Fin de la partida! El ganador del juego es... <b>{0}</b>. ¡¡¡Enhorabuena!!!'),
    ('GAME_END_ROUND', 'es', '¡Enhorabuena <b>{0}</b>! Tu carta <b>{1}</b> ha ganado la ronda <b>{2}</b>.\n\nLa carta negra de esta ronda era <b>{3}</b>\n\nLos jugadores eligieron las siguientes cartas blancas:\n<b>{4}</b>\n\nLas puntuaciones son las siguientes:\n<b>{5}</b>'),
    ('GAME_HELP', 'es', '	Bienvenido a la ayuda de {0} versión {1}\n\nPuedes consultar la ayuda en el siguiente enlace: {2}\n\nDisfrutad del bot y... ¡A jugar!\n\nCreado por {3}.'),
    ('GAME_JOIN_BUTTON', 'es', 'Unirse a la partida'),
    ('GAME_LEAVE', 'es', 'Dejar la partida'),
    ('GAME_LEFT', 'es', 'Has dejado la partida'),
    ('GAME_MODE_CLASSIC', 'es', 'Clásico'),
    ('GAME_MODE_DEMOCRACY', 'es', 'Democracia'),
    ('GAME_MODE_DICTATORSHIP', 'es', 'Dictadura'),
    ('GAME_PUNCTUATION_MODE', 'es', '\nSelecciona modo de puntuación:'),
    ('GAME_SELECTED_DICTIONARY', 'es', 'El mazo de cartas seleccionado es <b>{0}</b>.'),
    ('GAME_SELECTED_MAX_PLAYER_NUMBER', 'es', 'El número máximo de jugadores es <b>{0}</b>.'),
    ('GAME_SELECTED_MODE', 'es', 'El modo de juego es <b>{0}</b>.'),
    ('GAME_SELECTED_POINTS_TO_WIN', 'es', 'El número de puntos para ganar es <b>{0}</b>.'),
    ('GAME_SELECTED_ROUNDS_TO_END', 'es', 'El número de rondas es <b>{0}</b>.'),
    ('GAME_SELECT_CARD', 'es', '<b>Ronda {0}</b>\n\nLa carta negra de esta ronda es <b>{1}</b>\n\nAhora los jugadores jugaran sus cartas blancas por privado.'),
    ('GAME_SELECT_MAX_PLAYERS', 'es', '\nSelecciona nº máximo de jugadores:'),
    ('GAME_SELECT_MODE', 'es', '\nSelecciona modo de juego:'),
    ('GAME_START_BUTTON', 'es', 'Iniciar la partida'),
    ('GAME_TYPE_POINTS', 'es', 'Puntos'),
    ('GAME_TYPE_POINTS_SELECT', 'es', '\nSelecciona nº de puntos para ganar:'),
    ('GAME_TYPE_ROUNDS', 'es', 'Rondas'),
    ('GAME_TYPE_ROUNDS_SELECT', 'es', '\nSelecciona rondas de la partida:'),
    ('GAME_VOTE_CARD', 'es', '<b>Ronda {0}</b>\n\nLa carta negra de esta ronda es <b>{1}</b>\n\nLos jugadores eligieron las siguientes cartas blancas:\n\n<b>{2}</b>\n\nAhora los jugadores votaran por privado.'),
    ('GO_BACK', 'es', '← Volver'),
    ('PLAYER_CREATED_GAME', 'es', 'He creado la partida en el grupo, puedes configurarla allí'),
    ('PLAYER_JOINED', 'es', 'Te has unido a la partida.'),
    ('PLAYER_JOINING', 'es', 'Un momentito, estoy intentando unirte a la partida...'),
    ('PLAYER_SELECTED_CARD', 'es', '	<b>Ronda {0}</b>\n\nLa carta negra de esta ronda es:\n\n<b>{1}</b>\n\nHas elegido la carta blanca:\n\n<b>{2}</b>'),
    ('PLAYER_SELECT_CARD', 'es', '	<b>Ronda {0}</b>\n\nLa carta negra de esta ronda es:\n\n<b>{1}</b>\n\nDebes elegir una carta blanca de las siguientes:'),
    ('PLAYER_VOTED_CARD', 'es', '	<b>Ronda {0}</b>\n\nLa carta negra de esta ronda es:\n\n<b>{1}</b>\n\nHas elegido la carta blanca:\n\n<b>{2}</b>\n\nHas votado la carta blanca:\n\n<b>{3}</b>'),
    ('PLAYER_VOTED_DELETION', 'es', 'Has votado borrar la partida'),
    ('PLAYER_VOTE_CARD', 'es', '	<b>Ronda {0}</b>\n\nLa carta negra de esta ronda es:\n\n<b>{1}</b>\n\nHas elegido la carta blanca:\n\n<b>{2}</b>\n\nDebes votar una carta blanca de las siguientes:'),
    ('PLAYER_WELCOME', 'es', '¡Bienvenido! Acabo de añadirte a mi base de datos.\nSiempre que necesites ayuda puedes escribir /help\n¡Gracias por unirte!'),
    ('UNKNOWN_ERROR', 'es', 'Ha ocurrido un error inesperado.'),
    ('USER_LANG_CHANGE', 'es', 'Elige tu idioma:'),
    ('USER_LANG_CHANGED', 'es', 'Se ha cambiado el idioma.'),
    ('ACCEPT', 'en', 'Accept'),
    ('ALL_MESSAGES_SENT', 'en', 'All messages sent.'),
    ('CANCEL', 'en', 'Cancel'),
    ('CARDS_BLACK_ADD_BUTTON', 'en', 'Add black cards'),
    ('CARDS_BLACK_CARD_ADD', 'en', 'Answer me with the text of the black card you want to add.'),
    ('CARDS_BLACK_CARD_ADDED', 'en', 'Black card added successfully. You have {0} out of {1}.'),
    ('CARDS_BLACK_CARD_ADD_ANOTHER', 'en', 'Answer me with the text of the black card you want to add or type :cancel: to go back to the menu.'),
    ('CARDS_BLACK_CARD_DELETE', 'en', 'Answer me with the number of the white card you wish to delete.'),
    ('CARDS_BLACK_CARD_DELETED', 'en', 'Black card deleted succesfully.'),
    ('CARDS_BLACK_CARD_EDIT', 'en', 'Answer me with the id of the black card you want to edit.'),
    ('CARDS_BLACK_CARD_EDITED', 'en', 'Black card edited successfully.'),
    ('CARDS_BLACK_CARD_EDIT_NEW_TEXT', 'en', 'Answer me with the new text you want for that black card.'),
    ('CARDS_BLACK_EDIT_BUTTON', 'en', 'Edit black card'),
    ('CARDS_BLACK_LIST', 'en', 'On my way! There are the black cards. (It´s possible that they´re send in multiple messages)'),
    ('CARDS_BLACK_LIST_BUTTON', 'en', 'List black cards'),
    ('CARDS_BLACK_LIST_END', 'en', 'These are all the black cards.'),
    ('CARDS_BLACK_REMOVE_BUTTON', 'en', 'Delete black card'),
    ('CARDS_MENU', 'en', 'You are managing the cards of the dictionary: {0}'),
    ('CARDS_WHITE_ADD_BUTTON', 'en', 'Add white cards'),
    ('CARDS_WHITE_CARD_ADD', 'en', 'Answer me with the text of the white card you want to add.'),
    ('CARDS_WHITE_CARD_ADDED', 'en', 'White card added successfully. You have {0} out of {1}.'),
    ('CARDS_WHITE_CARD_ADD_ANOTHER', 'en', 'Answer me with the text of the white card you want to add or type :cancel: to go back to the menu.'),
    ('CARDS_WHITE_CARD_DELETE', 'en', 'Answer me with the id of the white card you want to delete.'),
    ('CARDS_WHITE_CARD_DELETED', 'en', 'White card deleted successfully.'),
    ('CARDS_WHITE_CARD_EDIT', 'en', 'Answer me with the id of the white card you want to edit.'),
    ('CARDS_WHITE_CARD_EDITED', 'en', 'White card edited successfully.'),
    ('CARDS_WHITE_CARD_EDIT_NEW_TEXT', 'en', 'Answer me with the new text you want for that white card.'),
    ('CARDS_WHITE_EDIT_BUTTON', 'en', 'Edit white card'),
    ('CARDS_WHITE_LIST', 'en', 'On my way! There are the white cards. (It´s possible that they´re send in multiple messages)'),
    ('CARDS_WHITE_LIST_BUTTON', 'en', 'List white cards'),
    ('CARDS_WHITE_LIST_END', 'en', 'These are all the white cards.'),
    ('CARDS_WHITE_REMOVE_BUTTON', 'en', 'Delete white card'),
    ('COLLABORATORS_ACCEPTED_CREATOR', 'en', '{0} has accepted to be collaborator.'),
    ('COLLABORATORS_ACCEPTED_MESSAGE', 'en', 'Perfect! You´re already a collaborator, now ask the bot´s creator to activate you.'),
    ('COLLABORATORS_ACCEPT_MESSAGE', 'en', '{0} has invited you to collaborate in their dictionary {1}.'),
    ('COLLABORATORS_ADD', 'en', 'Let´s go! Tell me the name (e.g. @cclhbot) or the ID (you can obtain it with the command /getmyid) from the user you want to activate/deactivate as collaborator.\n\n<b>WARNING: The collaborator you want to add must have initiated this bot first (texting /start in private.</b>'),
    ('COLLABORATORS_ADDED', 'en', 'A collaborator invitation has been sent to {0} successfully. You must now accept the invitation.'),
    ('COLLABORATORS_ADD_BUTTON', 'en', 'Add collaborator'),
    ('COLLABORATORS_DELETE', 'en', 'Let´s go! Tell me the name (e.g. @cclhbot) or the ID (you can obtain it with the command /getmyid) from the user you want to activate/deactivate as collaborator.'),
    ('COLLABORATORS_DELETED', 'en', 'The collaborator has been deleted succesfully.'),
    ('COLLABORATORS_DELETED_MESSAGE', 'en', 'You have been removed from the dictionary {0}'),
    ('COLLABORATORS_DELETE_BUTTON', 'en', 'Remove collaborator'),
    ('COLLABORATORS_LIST', 'en', 'These are the collaborators of this dictionary:\n\n{0}'),
    ('COLLABORATORS_LIST_BUTTON', 'en', 'List collaborators'),
    ('COLLABORATORS_MENU', 'en', 'You´re managing the collaborators of the dictionary: {0}'),
    ('COLLABORATORS_REJECTED_CREATOR', 'en', '{0} has rejected to be collaborator.'),
    ('COLLABORATORS_REJECTED_MESSAGE', 'en', 'You has rejected to be a collaborator.'),
    ('COLLABORATORS_TOGGLE', 'en', 'Let´s go! Tell me the name (e.g. @cclhbot) or the ID (you can obtain it with the command /getmyid) from the user you want to activate/deactivate as collaborator.'),
    ('COLLABORATORS_TOGGLED_OFF', 'en', 'The collaborator {0} has been toggled off.'),
    ('COLLABORATORS_TOGGLED_OFF_MESSAGE', 'en', 'You lost editing permissions in the dictionary {0}.'),
    ('COLLABORATORS_TOGGLED_ON', 'en', 'The collaborator {0} has been toggled on.'),
    ('COLLABORATORS_TOGGLED_ON_MESSAGE', 'en', 'You gained editing permissions in the dictionary {0}.'),
    ('COLLABORATORS_TOGGLE_BUTTON', 'en', 'Activate/Deactivate collaborator'),
    ('COLLABORATOR_ADD_ALREADY_EXISTS', 'en', 'That user is already a collaborator of this dictionary.'),
    ('COLLABORATOR_ADD_MAX_REACHED', 'en', 'This dictionary already has the maximum number of collaborators.'),
    ('COLLABORATOR_ADD_USER_DOESNT_EXISTS', 'en', 'There is no user with that name.'),
    ('DICTIONARIES_CHANGE_LANG_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to change its language'),
    ('DICTIONARIES_CREATE_BUTTON', 'en', 'Create dictionary'),
    ('DICTIONARIES_DELETE_BUTTON', 'en', 'Delete dictionary'),
    ('DICTIONARIES_DELETE_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to borrar.'),
    ('DICTIONARIES_HELP', 'en', 'Welcome to the help menu. You are playing {0} version {1}\n\nYou can check the help documentation in this link: {2}\n\nShare your dictionaries!!\n\n\nCreated by {3}.'),
    ('DICTIONARIES_LANG_BUTTON', 'en', 'Change language'),
    ('DICTIONARIES_LIST', 'en', ' These are the dictionaries that you have created or you are collaborator:\n\n{0}'),
    ('DICTIONARIES_LIST_BUTTON', 'en', 'List my dictionaries'),
    ('DICTIONARIES_MAIN_MENU', 'en', 'Hi! I´m the bot that will help you creating and managing dictionaries for CCLHBot.\nThis are the actions that you can do:'),
    ('DICTIONARIES_MANAGE_CARDS_BUTTON', 'en', 'Manage cards'),
    ('DICTIONARIES_MANAGE_CARDS_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to edit its cards.'),
    ('DICTIONARIES_MANAGE_COLLABORATORS_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to edit its collaborators.'),
    ('DICTIONARIES_MANAGE_COLLABS_BUTTON', 'en', 'Manage collaborators'),
    ('DICTIONARIES_RENAME_BUTTON', 'en', 'Rename dictionary'),
    ('DICTIONARIES_RENAME_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to rename.'),
    ('DICTIONARIES_SHARE_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to share/unshare.'),
    ('DICTIONARIES_TOGGLE_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to publish/unpublish.'),
    ('DICTIONARIES_TOGGLE_PUBLISH_BUTTON', 'en', 'Publish/unpublish dictionary'),
    ('DICTIONARIES_TOGGLE_SHARE_BUTTON', 'en', 'Share/unshare dictionary'),
    ('DICTIONARY_CHANGE_LANG', 'en', 'Answer me with the language code you want to choose:\n{0}'),
    ('DICTIONARY_CREATE', 'en', 'OK! Answer me with the name of the dictionary you want to create.'),
    ('DICTIONARY_CREATED', 'en', 'Your dictionary have been successfully created, no go to the ´Manage cards´ menu to add cards.'),
    ('DICTIONARY_DELETE', 'en', '<b>ATTENTION! This dictionary is PUBLISHED</b>. The dictionary will be deleted and also its <b>cards</b> too.\n\n¿Are you COMPLETELY sure you want to delete it?\n· Answer YES to delete it.\n· Answer anything else or ignore the message to reject.'),
    ('DICTIONARY_DELETED', 'en', 'Your dictionary have been successfully deleted.'),
    ('DICTIONARY_DELETE_CANCELLED', 'en', 'You have cancelled the deletion of the dictionary.'),
    ('DICTIONARY_LANG_CHANGED', 'en', 'The language of your dictionary have been successfully changed.'),
    ('DICTIONARY_RENAME', 'en', 'OK! Answer me with the new name of the dictionary you want to rename.'),
    ('DICTIONARY_RENAMED', 'en', 'Your dictionary have been successfully renamed.'),
    ('DICTIONARY_SHARED_OFF', 'en', 'You have unshared the dictionary {0} sucessfully.'),
    ('DICTIONARY_SHARED_OFF_REQUEST', 'en', 'You have requested to unshare dictionary {0}.'),
    ('DICTIONARY_SHARED_ON', 'en', 'You have shared the dictionary {0} sucessfully.'),
    ('DICTIONARY_SHARED_ON_REQUEST', 'en', 'You have requested to share dictionary {0}.'),
    ('DICTIONARY_SHARED_REJECTED', 'en', 'You have rejected to share the dictionary {0}.'),
    ('DICTIONARY_TOGGLED_OFF', 'en', 'You have unpublished the dictionary {0} sucessfully.'),
    ('DICTIONARY_TOGGLED_ON', 'en', 'You have published the dictionary {0} sucessfully.'),
    ('DICTIONARY_INFO', 'en', '{0} - {1} (<b>yours:</b> {2}; <b>published:</b> {3}; <b>shared:</b> {4}; <b>language:</b> {5})'),
    ('COLLABORATOR_INFO', 'en', '{0} (accepted: {1}, active: {2})'),
    ('COLLABORATORS_LIST_EMPTY', 'en', 'There are no collaborators.'),
    ('CARD_INFO', 'en', '{0} - {1}'),
    ('YES', 'en', 'Yes'),
    ('NO', 'en', 'No'),
    ('ERROR_SELECTION_INVALID', 'en', 'I could not find that. Reply with the number shown on the left of the list.'),
    ('GAME_GLOBAL_MESSAGES_ON', 'en', 'Global messages enabled.'),
    ('GAME_GLOBAL_MESSAGES_OFF', 'en', 'Global messages disabled.'),
    ('ERROR_CARD_ALREADY_PLAYED', 'en', 'That card has already been played.'),
    ('ERROR_CARD_ALREADY_VOTED', 'en', 'That card has already been voted.'),
    ('ERROR_CARD_NOT_PLAYED', 'en', 'That card has not been played this round.'),
    ('ERROR_PLAYER_CANNOT_PLAY_CARD', 'en', 'You cannot play that card.'),
    ('ERROR_PLAYER_CANNOT_VOTE_CARD', 'en', 'You cannot vote for that card.'),
    ('ERROR_ROUND_PRESIDENT_CANNOT_PLAY_CARD', 'en', 'This round you pick the winning card, you do not play one.'),
    ('ERROR_ROUND_NOT_FOUND', 'en', 'This round is no longer in play.'),
    ('ERROR_ROUND_NOT_STARTED', 'en', 'The round has not started yet.'),
    ('ERROR_ROUND_NOT_ENDING', 'en', 'The round has not finished yet.'),
    ('ERROR_ROUND_WRONG_STATUS', 'en', 'That action does not apply to this round right now.'),
    ('ERROR_GAME_NOT_FOUND', 'en', 'There is no game in this group.'),
    ('ERROR_GAME_ALREADY_EXISTS', 'en', 'There is already a game in this group.'),
    ('ERROR_GAME_CREATOR_ALREADY_EXISTS', 'en', 'You already have a game open in another group.'),
    ('ERROR_GAME_CREATOR_CANNOT_LEAVE', 'en', 'You created this game: you cannot leave it, but you can delete it.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_PERFORM_ACTION', 'en', 'Only the player who created the game can do that.'),
    ('ERROR_GAME_ROOM_DOESNT_EXISTS', 'en', 'I cannot find this group.'),
    ('ERROR_ROOM_NOT_ACTIVE', 'en', 'This group is disabled.'),
    ('ERROR_PLAYER_NOT_FOUND', 'en', 'You are not in this game.'),
    ('ERROR_PLAYER_ALREADY_EXISTS', 'en', 'You are already in this game.'),
    ('ERROR_PLAYER_CANNOT_VOTE_DELETION', 'en', 'You cannot vote to delete this game.'),
    ('ERROR_USER_NOT_ACTIVE', 'en', 'Your user is disabled. Send me /start in a private chat.'),
    ('ERROR_USER_ALREADY_EXISTS', 'en', 'You are already registered.'),
    ('ERROR_CANT_FIND_WINNER_CARD', 'en', 'Cannot find winner card.'),
    ('ERROR_CARD_ALREADY_EXISTS', 'en', 'There already exists a card with the same text in this dictionary.'),
    ('ERROR_CARD_DOESNT_EXISTS', 'en', 'The card you´re trying to edit does not exist.'),
    ('ERROR_CARD_EXCEEDED_LENGTH', 'en', 'The card exceeds the maximum of {0} characters.'),
    ('ERROR_CARD_NOT_YOURS', 'en', 'This card is not yours.'),
    ('ERROR_COLLABORATOR_ADD_ALREADY_EXISTS', 'en', 'The user you are trying to add is already a collaborator in this dictionary.'),
    ('ERROR_COLLABORATOR_ADD_MAX_REACHED', 'en', 'You have reached the maximum number of collaborators and you can´t add any more.'),
    ('ERROR_COLLABORATOR_ADD_USER_DOESNT_EXISTS', 'en', 'The user that you´re trying to add as collaborator is incorrect or it´s not registered on the bot.'),
    ('ERROR_COLLABORATOR_DOESNT_EXISTS', 'en', 'The user is incorrect or is not registered on the bot.'),
    ('ERROR_COLLABORATOR_REMOVE_USER_DOESNT_EXISTS', 'en', 'The user that you´re trying to delete as collaborator is incorrect or it´s not a collaborator in this dictionary.'),
    ('ERROR_COMMAND_SHOULD_BE_ON_GROUP', 'en', 'This command must be sent in a group in which the bot is.'),
    ('ERROR_COMMAND_SHOULD_BE_ON_PRIVATE', 'en', 'This command must be sent privately to the bot.'),
    ('ERROR_DICTIONARY_COLLAB_CREATOR_CANT_BE_ALTERED', 'en', 'The dictionary creator cannot be altered as a collaborator.'),
    ('ERROR_DICTIONARY_ALREADY_EXISTS', 'en', 'There is already a dictionary with this name.'),
    ('ERROR_DICTIONARY_ALREADY_FILLED', 'en', 'You can´t add more kind of cards to this dictionary.'),
    ('ERROR_DICTIONARY_ALREADY_PUBLISHED', 'en', 'You can´t edit a dictionary that it´s already published. Unpublish it to edit it.'),
    ('ERROR_DICTIONARY_ALREADY_SHARED', 'en', 'You can´t modify a dictionary that it´s already shared. Contact {0} to unpublish it.'),
    ('ERROR_DICTIONARY_NOT_FILLED', 'en', 'You can´t publish the dictionary because due to a lack of cards.'),
    ('ERROR_DICTIONARY_NOT_FOUND', 'en', 'This dictionary doesn´t exist.'),
    ('ERROR_DICTIONARY_NOT_PUBLISHED', 'en', 'You can´t share a dictionary that it´s no published. Publish it to share it.'),
    ('ERROR_DICTIONARY_NOT_YOURS', 'en', 'That dictionary doesn´t belong to you.'),
    ('ERROR_DICTIONARY_SHARED', 'en', 'The dictionary is shared, contact {0} to delete it.'),
    ('ERROR_GAME_ALREADY_CREATED', 'en', 'There is an active game in this group or the creator has an active game on another group.'),
    ('ERROR_GAME_ALREADY_FILLED', 'en', 'The game has already reached the maximum of players.'),
    ('ERROR_GAME_ALREADY_STARTED', 'en', 'The game has already started.'),
    ('ERROR_GAME_DOESNT_EXISTS', 'en', 'There is no game initiated in this group.'),
    ('ERROR_GAME_NOT_FILLED', 'en', 'The game has not reached the minimum number of players.'),
    ('ERROR_GAME_NOT_STARTED', 'en', 'The game has not started.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_CONFIGURE', 'en', 'Only the creator can configure it.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_DELETE', 'en', 'Only the creator can delete it.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_START', 'en', 'Only the creator can start the game.'),
    ('ERROR_GAME_USER_DOESNT_EXISTS', 'en', 'You are not registered. Input /start in private.'),
    ('ERROR_PLAYER_ALREADY_JOINED', 'en', 'Ya estas participando en esta partida.'),
    ('ERROR_PLAYER_ALREADY_PLAYED_CARD', 'en', 'You have already played a card.'),
    ('ERROR_PLAYER_ALREADY_PLAYING', 'en', 'You are already playing a game.'),
    ('ERROR_PLAYER_ALREADY_VOTED_CARD', 'en', 'You have already voted for a card.'),
    ('ERROR_PLAYER_ALREADY_VOTED_DELETION', 'en', 'You have already voted to delete this game.'),
    ('ERROR_PLAYER_DOES_NOT_EXISTS', 'en', 'You have not joined any game.'),
    ('ERROR_PLAYER_NO_GAMES', 'en', 'You have no active games.'),
    ('ERROR_UNKNOWN', 'en', 'Unknown error.'),
    ('ERROR_USER_ALREADY_REGISTERED', 'en', 'You´re already registered. Write /help for more information.'),
    ('GAME_CHANGE_DICTIONARY', 'en', 'Change dictionary.'),
    ('GAME_CHANGE_GAME_MODE', 'en', 'Change game mode'),
    ('GAME_CHANGE_MAX_N_PLAYERS', 'en', 'Change number of max players.'),
    ('GAME_CHANGE_PUNCTUATION_MODE', 'en', 'Change punctuation mode.'),
    ('GAME_CONFIGURE_BUTTON', 'en', 'Configure game'),
    ('GAME_CREATED_CURRENT_PLAYER_NUMBER', 'en', '<b>{0}</b> players have joined:'),
    ('GAME_CREATED_CURRENT_VOTE_DELETION_NUMBER', 'en', '<b>{0}</b> player/s have voted to delete the game.'),
    ('GAME_CREATED_GROUP', 'en', 'I already created the game!'),
    ('GAME_CREATING', 'en', 'Hold on, I´m creating the game...'),
    ('GAME_DELETED', 'en', 'Game deleted.'),
    ('GAME_DELETE_BUTTON', 'en', 'Delete game'),
    ('GAME_DELETION_ALL', 'en', 'All games have been deleted.'),
    ('GAME_DELETION_FORCED', 'en', 'Sorry, the game has been deleted by an admin. You can start a new game.'),
    ('GAME_DELETION_USER', 'en', '{0}´s game has been deleted.'),
    ('GAME_DICTIONARY_SELECT', 'en', '\nSelect dictionary:'),
    ('GAME_END_GAME', 'en', 'Game! The winner is... <b>{0}</b>. Congratulations!!!'),
    ('GAME_END_ROUND', 'en', 'Congratulations <b>{0}</b>! Your card <b>{1}</b> has won the round <b>{2}</b>.\n\nThe black card of this round was <b>{3}</b>\n\nThe players chose the following white cards:\n<b>{4}</b>\n\nThe score is the following:\n<b>{5}</b>'),
    ('GAME_HELP', 'en', 'Welcome to the help menu of {0} version {1}\n\nYou can check for help here: {2}\n\nEnjoy the bot and... Let´s play!\n\nMade by {3}.'),
    ('GAME_JOIN_BUTTON', 'en', 'Join game'),
    ('GAME_LEAVE', 'en', 'Leave game'),
    ('GAME_LEFT', 'en', 'You left the game.'),
    ('GAME_MODE_CLASSIC', 'en', 'Classic'),
    ('GAME_MODE_DEMOCRACY', 'en', 'Democracy'),
    ('GAME_MODE_DICTATORSHIP', 'en', 'Dictatorship'),
    ('GAME_PUNCTUATION_MODE', 'en', '\nSelect score mode:'),
    ('GAME_SELECTED_DICTIONARY', 'en', 'The dictionary selected is <b>{0}</b>.'),
    ('GAME_SELECTED_MAX_PLAYER_NUMBER', 'en', 'The maximum number of players is <b>{0}</b>.'),
    ('GAME_SELECTED_MODE', 'en', 'The game mode is <b>{0}</b>.'),
    ('GAME_SELECTED_POINTS_TO_WIN', 'en', 'The number of points to win is <b>{0}</b>.'),
    ('GAME_SELECTED_ROUNDS_TO_END', 'en', 'The number of rounds is <b>{0}</b>.'),
    ('GAME_SELECT_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of this round is <b>{1}</b>\n\nNow the players will play their white cards in private.'),
    ('GAME_SELECT_MAX_PLAYERS', 'en', '\nSelect max number of players:'),
    ('GAME_SELECT_MODE', 'en', '\nSelect game mode:'),
    ('GAME_START_BUTTON', 'en', 'Start game'),
    ('GAME_TYPE_POINTS', 'en', 'Points'),
    ('GAME_TYPE_POINTS_SELECT', 'en', '\nSelect number of points to win:'),
    ('GAME_TYPE_ROUNDS', 'en', 'Rounds'),
    ('GAME_TYPE_ROUNDS_SELECT', 'en', '\nSelect rounds of the game:'),
    ('GAME_VOTE_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of this round is <b>{1}</b>\n\nThe players chose the following white cards: \n\n<b>{2}</b>\n\nNow the players will vote in private.'),
    ('GO_BACK', 'en', '← Go back'),
    ('PLAYER_CREATED_GAME', 'en', 'I created a game in the group, you can configure it there.'),
    ('PLAYER_JOINED', 'en', 'You joined the game.'),
    ('PLAYER_JOINING', 'en', 'Hold on, you are joining the game...'),
    ('PLAYER_SELECTED_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of the round is:\n\n<b>{1}</b>\n\nYou chose this white card:\n\n<b>{2}</b>'),
    ('PLAYER_SELECT_CARD', 'en', '<b>Ronda {0}</b>\n\nThe black card of this round is:\n\n<b>{1}</b>\n\nYou have to choose a white card of the following:'),
    ('PLAYER_VOTED_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of the round is:\n\n<b>{1}</b>\n\nYou chose this white card:\n\n<b>{2}</b>\n\nYou voted the white card:\n\n<b>{3}</b>'),
    ('PLAYER_VOTED_DELETION', 'en', 'You voted to delete the game.'),
    ('PLAYER_VOTE_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of the round is:\n\n<b>{1}</b>\n\nYou chose the white card:\n\n<b>{2}</b>\n\nYou have to vote one of the following cards:'),
    ('PLAYER_WELCOME', 'en', 'Welcome! I just added you to my database.\nWhen you need help you only have to send me the command /help\nThank you for joining!'),
    ('UNKNOWN_ERROR', 'en', 'An unexpected error occurred.'),
    ('USER_LANG_CHANGE', 'en', 'Choose your language:'),
    ('USER_LANG_CHANGED', 'en', 'Language changed successfully.');
